/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_Server */

#ifndef _Included_hello_Server
#define _Included_hello_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_Server
 * Method:    Enc
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_hello_Server_Enc
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     hello_Server
 * Method:    Dec
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_hello_Server_Dec
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
