/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Client */

#ifndef _Included_Client
#define _Included_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Client
 * Method:    Enc
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Client_Enc
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Client
 * Method:    Dec
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Client_Dec
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
